title: Luke Opperman
description: Constructor

url: http://luke.opperman.net
baseurl: ""
paginate_path: "blog/page:num/"
permalink: blog/:year/:month/:title/

markdown: redcarpet
highlighter: pygments
paginate: 5

navigation:
 - title: Home
   url: /
 - title: About
   url: /about.html

social:
   github: loppear
   twitter: loppear
   facebook: loppear
   email: blog@luke.opperman.net

google_analytics: "UA-64601310-1"
